docker-compose-yaml: docker-compose.yml

project: drupal-example

tasks:
#   pre-rollout:
#     - run:
#         name: drush sql-dump
#         command: mkdir -p /app/web/sites/default/files/private/ && drush sql-dump --ordered-dump --gzip --result-file=/app/web/sites/default/files/private/pre-deploy-dump.sql.gz || true
#         service: cli

  post-rollout:
    - run:
        name: IF no Drupal installed and we install umami
        command: |
            if tables=$(drush sqlq 'show tables;') && [ -z "$tables" ]; then
                # no drupal installed, install umami and some other things
                drush -y si demo_umami --force
                drush -y upwd admin --password=admin
                drush -y en admin_toolbar
                drush -y config-set system.site name 'Drupal4Gov Training - sponsored by amazee.io'
            fi
        service: cli
        shell: bash
    - run:
        name: drush updb
        command: drush -y updb
        service: cli
    - run:
        name: drush cr
        command: drush -y cr
        service: cli



environments:
  master:
    cronjobs:
      - name: drush cron
        schedule: "*/15 * * * *"
        command: drush cron
        service: cli
